package dynablaster;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JPanel;
import javax.swing.Timer;

public class MainPanel extends JPanel {

    private final Image gracz;
    private int x;
    private int y;
    private final Timer moveTimer;
    private int xDelta;
    private int yDelta;

    public MainPanel() {
        initComponents();

        final Toolkit toolkit = Toolkit.getDefaultToolkit();
        gracz = toolkit.getImage("gracz.png");

        KeyListenerWrapper listener = KeyListenerWrapper.init(new KeyAdapter() {
            private int latestKeyPressedCode;

            @Override
            public void keyPressed(KeyEvent e) {
                latestKeyPressedCode = e.getKeyCode();
                switch (e.getKeyCode()) {
                    case KeyEvent.VK_UP:
                        xDelta = 0;
                        yDelta = -2;
                        break;
                    case KeyEvent.VK_DOWN:
                        xDelta = 0;
                        yDelta = 2;
                        break;
                    case KeyEvent.VK_LEFT:
                        xDelta = -2;
                        yDelta = 0;
                        break;
                    case KeyEvent.VK_RIGHT:
                        xDelta = 2;
                        yDelta = 0;
                        break;
                    default:
                        break;
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
                switch (e.getKeyCode()) {
                    case KeyEvent.VK_UP:
                    case KeyEvent.VK_DOWN:
                    case KeyEvent.VK_LEFT:
                    case KeyEvent.VK_RIGHT:
                        if (latestKeyPressedCode == e.getKeyCode()) {
                            xDelta = 0;
                            yDelta = 0;
                        }
                        break;
                    default:
                        return;
                }
            }

        }, false);

        addKeyListener(listener);

        moveTimer = new Timer(17, (ActionEvent) -> {
            x += xDelta;
            y += yDelta;

            if (y < 0) {
                y = 0;
            } else if (y + 23 > 230) {
                y = 230 - 23;
            }

            if (x < 0) {
                x = 0;
            } else if (x + 23 > 230) {
                x = 230 - 23;
            }

            repaint();
        });
        moveTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(Color.GREEN);
        g2.fillRect(0, 0, 23 * 10, 23 * 10);
        g2.drawImage(gracz, x, y, this);

        Toolkit.getDefaultToolkit().sync();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
