package dynablaster;

public class MainFrame extends javax.swing.JFrame {
    
    private final GameController gameController = new GameController(this);

    public MainFrame() {
        initComponents();

        endGame.setVisible(false);
        playerSelection.setVisible(true);

        gamePanel.requestFocusInWindow();
        gamePanel.setVisible(false);
        
        gamePanel.setGameController(gameController);
        playerSelection.setGameController(gameController);
        endGame.setGameController(gameController);
    }
    
    public void showPlayerSelectionPanel() {
        gamePanel.setVisible(false);
        endGame.setVisible(false);
        
        playerSelection.setVisible(true);
    }

    public void showEndPanel(Player winner) {
        gamePanel.setVisible(false);
        playerSelection.setVisible(false);
        
        endGame.setVisible(true);
        endGame.displayWinner(winner);
    }

    public void showGamePanel() {
        endGame.setVisible(false);
        playerSelection.setVisible(false);
        
        gamePanel.setVisible(true);
        gamePanel.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endGame = new dynablaster.EndGamePanel();
        playerSelection = new dynablaster.PlayerSelectionPanel();
        gamePanel = new dynablaster.MainPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dyna Blaster");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        endGame.setPreferredSize(gamePanel.getPreferredSize());
        getContentPane().add(endGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        playerSelection.setPreferredSize(gamePanel.getPreferredSize());
        getContentPane().add(playerSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 416, Short.MAX_VALUE)
        );

        getContentPane().add(gamePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dynablaster.EndGamePanel endGame;
    private dynablaster.MainPanel gamePanel;
    private dynablaster.PlayerSelectionPanel playerSelection;
    // End of variables declaration//GEN-END:variables
}
