package dynablaster;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JCheckBox;

public class PlayerSelectionPanel extends javax.swing.JPanel {

    private GameController gameController;
    private final List<JCheckBox> playerCheckBoxes = new ArrayList<>();

    public PlayerSelectionPanel() {
        initComponents();

        playerCheckBoxes.add(whitePlayer);
        playerCheckBoxes.add(greenPlayer);
        playerCheckBoxes.add(redPlayer);
        playerCheckBoxes.add(bluePlayer);
    }

    public void setGameController(GameController controller) {
        gameController = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whitePlayer = new javax.swing.JCheckBox();
        greenPlayer = new javax.swing.JCheckBox();
        redPlayer = new javax.swing.JCheckBox();
        bluePlayer = new javax.swing.JCheckBox();
        newGameButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        whitePlayer.setSelected(true);
        whitePlayer.setText("Biały [Strałki + Spacja]");
        whitePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whitePlayerActionPerformed(evt);
            }
        });

        greenPlayer.setSelected(true);
        greenPlayer.setText("Zielony [WASD + Q]");
        greenPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenPlayerActionPerformed(evt);
            }
        });

        redPlayer.setText("Czerwony [IJKL + U]");
        redPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redPlayerActionPerformed(evt);
            }
        });

        bluePlayer.setText("Niebieski [Numeryczne 8426 + 5]");
        bluePlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bluePlayerActionPerformed(evt);
            }
        });

        newGameButton.setText("Nowa Gra");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wybór graczy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(greenPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(redPlayer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bluePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whitePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(92, 92, 92)
                .addComponent(whitePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greenPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(redPlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bluePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(107, 107, 107)
                .addComponent(newGameButton)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        gameController.newGame();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void greenPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenPlayerActionPerformed
        playerCheckboxToggled((JCheckBox) evt.getSource(), PlayerColor.GREEN);
    }//GEN-LAST:event_greenPlayerActionPerformed

    private void redPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redPlayerActionPerformed
        playerCheckboxToggled((JCheckBox) evt.getSource(), PlayerColor.RED);
    }//GEN-LAST:event_redPlayerActionPerformed

    private void bluePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bluePlayerActionPerformed
        playerCheckboxToggled((JCheckBox) evt.getSource(), PlayerColor.BLUE);
    }//GEN-LAST:event_bluePlayerActionPerformed

    private void whitePlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whitePlayerActionPerformed
        playerCheckboxToggled((JCheckBox) evt.getSource(), PlayerColor.WHITE);
    }//GEN-LAST:event_whitePlayerActionPerformed

    private void playerCheckboxToggled(JCheckBox checkBox, PlayerColor color) {
        requireAtLeastTwoPlayers(checkBox);
        gameController.players.setPlayerEnabled(color, checkBox.isSelected());
    }
    
    private void requireAtLeastTwoPlayers(JCheckBox checkBox) {
        if (checkBox.isSelected()) {
            return;
        }

        int checkedCount = 0;
        for (JCheckBox playerCheckBox : playerCheckBoxes) {
            if (playerCheckBox.isSelected()) {
                checkedCount += 1;
            }
        }

        if (checkedCount < 2) {
            checkBox.setSelected(true);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bluePlayer;
    private javax.swing.JCheckBox greenPlayer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton newGameButton;
    private javax.swing.JCheckBox redPlayer;
    private javax.swing.JCheckBox whitePlayer;
    // End of variables declaration//GEN-END:variables
}
